# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Qpushbtn.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def chkbtn(self):
        if self.b1.isChecked()==True:
            self.b1.setText("Pressed")
        else:
            self.b1.setText("Released")
    def btnstate(self,b):
        print("Caption of button pressed :",b.text())
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(580, 387)
        self.b1 = QtWidgets.QPushButton(Form)
        self.b1.setGeometry(QtCore.QRect(180, 90, 141, 71))
        self.b1.setObjectName("b1")
        self.b2 = QtWidgets.QPushButton(Form)
        self.b2.setGeometry(QtCore.QRect(200, 190, 93, 28))
        self.b2.setObjectName("b2")
        self.b3 = QtWidgets.QPushButton(Form)
        self.b3.setGeometry(QtCore.QRect(200, 240, 93, 28))
        self.b3.setObjectName("b3")
        self.b1.clicked.connect(self.chkbtn)
        self.b2.clicked.connect(self.btnstate)
        self.b3.clicked.connect(self.btnstate)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.b1.setText(_translate("Form", "Push Button"))
        self.b2.setText(_translate("Form", "PushButton"))
        self.b3.setText(_translate("Form", "PushButton"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
